from setuptools import setup, find_packages

setup(
    name="multi-agent-rl",
    version="1.0.0",
    description="A comprehensive multi-agent reinforcement learning framework",
    author="Your Name",
    author_email="your.email@example.com",
    packages=find_packages(),
    install_requires=[
        "torch>=2.0.0",
        "numpy>=1.21.0",
        "matplotlib>=3.5.0",
        "seaborn>=0.11.0",
        "gym>=0.21.0",
        "gymnasium>=0.28.0",
        "tensorboard>=2.10.0",
        "tqdm>=4.64.0",
        "scipy>=1.9.0",
        "pandas>=1.4.0",
        "plotly>=5.10.0",
        "jupyter>=1.0.0",
        "ipywidgets>=8.0.0",
    ],
    python_requires=">=3.8",
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
    ],
)